### ISSUE TITLE
[BUG] NPE when trying to parse catalog with 0.4.1 and 0.4.2

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-backend#336]
**Describe the bug**

Only one item is showing up in catalog in UI, the knative ones.  (and also the EIPs)

**To Reproduce**
1. Download native executable 
2. Start it

**Expected behavior**

**Logs**
```
2022-11-28 11:50:08,454 INFO  [io.kao.bac.api.met.cat.AbstractCatalog] (ForkJoinPool.commonPool-worker-1) Catalog warmed up.
2022-11-28 11:50:11,536 ERROR [io.kao.bac.met.par.JarParseCatalog] (ForkJoinPool.commonPool-worker-1) Error trying to parse catalog.: java.lang.NullPointerException: in is null
	at java.util.zip.ZipInputStream.<init>(ZipInputStream.java:103)
	at java.util.zip.ZipInputStream.<init>(ZipInputStream.java:82)
	at io.kaoto.backend.metadata.parser.JarParseCatalog.getJarAndParse(JarParseCatalog.java:53)
	at io.kaoto.backend.metadata.parser.JarParseCatalog.lambda$parse$2(JarParseCatalog.java:129)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
	at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:705)
	at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
```
**Environment (please complete the following information):**
 - OS: [e.g. "Linux 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux"]
 - Output of the mvn -version` command
 - Kaoto Version [e.g. 1.0]

**Additional context**

tried only with native executable so far (both Windows and Linux)

**Comment by apupier** [comment]
sound suspicious to have a different version here https://github.com/KaotoIO/kaoto-backend/blob/151455ee67229e5bfe67dac0a08e285cdb58b8a5/api/src/main/resources/application.yaml#L17 than here https://github.com/KaotoIO/kaoto-backend/blob/main/api/src/main/resources/resources-config.json#L8

**Comment by apupier** [comment]
I guess this kind of problem coudl be caught only with an integration test: https://quarkus.io/guides/getting-started-testing#quarkus-integration-test
