### ISSUE TITLE
[BUG] Native binary for 0.5.0 does not contain kamelet catalog

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-backend#383]
**Describe the bug**

```
2022-12-14 11:31:12,260 ERROR [io.kao.bac.met.par.JarParseCatalog] (ForkJoinPool.commonPool-worker-1) Error trying to parse catalog.: java.lang.NullPointerException: in is null
	at java.base@17.0.5/java.util.zip.ZipInputStream.<init>(ZipInputStream.java:103)
	at java.base@17.0.5/java.util.zip.ZipInputStream.<init>(ZipInputStream.java:82)
	at io.kaoto.backend.metadata.parser.JarParseCatalog.getJarAndParse(JarParseCatalog.java:53)
	at io.kaoto.backend.metadata.parser.JarParseCatalog.lambda$parse$2(JarParseCatalog.java:129)
	at java.base@17.0.5/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base@17.0.5/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base@17.0.5/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base@17.0.5/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base@17.0.5/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base@17.0.5/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base@17.0.5/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
```

similar regression than https://github.com/KaotoIO/kaoto-backend/issues/336

**To Reproduce**

**Expected behavior**

**Logs**
If applicable, add logs to help explain your problem.

**Environment (please complete the following information):**
 - OS: [e.g. "Linux 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux"]
 - Output of the mvn -version` command
 - Kaoto Version [e.g. 1.0]

**Additional context**

wondering why the previously provided test did not caught it https://github.com/KaotoIO/kaoto-backend/pull/338/files#diff-fe37dc73058230f89b616a353de09c14768fc55476a6a64256bbcbbf3e92e191R19

**Comment by apupier** [comment]
already fixed on main branch.

The commit which is supposed to update the version is part of no branch:

![image](https://user-images.githubusercontent.com/1105127/207575402-1a5162e6-f534-4ba0-9e17-82566e9849b5.png)

The tag source code contains 0.9.3 for kamelet https://github.com/KaotoIO/kaoto-backend/blob/1d389bf66486b99d54278c0ceb93791496f146e1/api/src/main/resources/application.yaml#L5 in application.yaml but the kametet jar is 0.10.0 https://github.com/KaotoIO/kaoto-backend/blob/v0.5.0/api/src/main/resources/camel-kamelets-0.10.0.jar

With blame, we can find that the commit that did the change is this one https://github.com/KaotoIO/kaoto-backend/commit/2f3cc3705c7a81cf61ca7682fb8acc9f4e5412e5 (also marked as nelongign to any commit.

it seems like some parts of the history has been rewritten
