### ISSUE TITLE
[BUG]NPE CamelRouteDeploymentGeneratorService.validationSchema(CamelRouteDeploymentGeneratorService.java:62) with native binary with 0.6.0

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-backend#426]
**Describe the bug**

With 0.6.0 native binary, the Kaoto backend is not responding to requests. The kaoto UI stays with spinning "Trying to reach Kaoto backend"

With 0.6.0, the server has this error:
`ERROR [io.kao.bac.api.res.v1.CapabilitiesResource] (executor-thread-0) Error getting capabilities.`

With  https://github.com/KaotoIO/kaoto-backend/pull/425 , the stack is:
```
ERROR [io.kao.bac.api.res.v1.CapabilitiesResource] (executor-thread-0) Error getting capabilities.: java.lang.NullPointerException
	at io.kaoto.backend.api.service.deployment.generator.camelroute.CamelRouteDeploymentGeneratorService.validationSchema(CamelRouteDeploymentGeneratorService.java:62)
	at io.kaoto.backend.api.service.deployment.generator.camelroute.CamelRouteDeploymentGeneratorService_ClientProxy.validationSchema(Unknown Source)
	at io.kaoto.backend.api.service.language.LanguageService.getAll(LanguageService.java:49)
	at io.kaoto.backend.api.service.language.LanguageService_Subclass.getAll$$superforward1(Unknown Source)
	at io.kaoto.backend.api.service.language.LanguageService_Subclass$$function$$1.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.opentelemetry.runtime.tracing.cdi.WithSpanInterceptor.span(WithSpanInterceptor.java:66)
	at io.quarkus.opentelemetry.runtime.tracing.cdi.WithSpanInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:33)
	at io.kaoto.backend.api.service.language.LanguageService_Subclass.getAll(Unknown Source)
	at io.kaoto.backend.api.service.language.LanguageService_ClientProxy.getAll(Unknown Source)
	at io.kaoto.backend.api.resource.v1.CapabilitiesResource.getAll(CapabilitiesResource.java:63)
	at io.kaoto.backend.api.resource.v1.CapabilitiesResource_ClientProxy.getAll(Unknown Source)
	at io.kaoto.backend.api.resource.v1.CapabilitiesResource$quarkusrestinvoker$getAll_93f0592003cb2534bd0846f4b00d0c6ee0070902.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:114)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
```

**To Reproduce**
1. Start kaoto backend binary 0.6.0
2. Start Kaoto UI 0.6.0

**Expected behavior**

**Logs**
If applicable, add logs to help explain your problem.

**Environment (please complete the following information):**
 - OS: Fedora
 - Output of the mvn -version` command
 - Kaoto Version 0.6.0

**Additional context**

it is working fine with Java mode

**Comment by apupier** [comment]
the resource camel-yaml-dsl.json is missing from binary
