### ISSUE TITLE
Error processing deployment when deploying an integration to Kubernetes

### ISSUE THREAD

**Issue by astefanutti** [KaotoIO/kaoto-backend#481]
**Describe the bug**

An exception occurs when deploying an integration to a Kubernetes cluster.

**To Reproduce**

1. Create an integration, e.g., from a timer to a log:
```yaml
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: test
spec:
  flows:
  - from:
      uri: timer:timer
      parameters:
        time: '1000'
      steps:
      - to:
          uri: log:log
```
2. Deploy the integration

**Expected behavior**

The integration should deploy correctly.

**Logs**

```
2023-02-23 16:10:04,272 ERROR [io.kao.bac.api.res.v1.DeploymentsResource] (executor-thread-3) Error processing deployment.: could not determine a constructor for the tag tag:yaml.org,2002:io.kaoto.backend.model.deployment.camelroute.IntegrationSpec
 in 'reader', line 5, column 7:
    spec: !!io.kaoto.backend.model.deploym ... 
          ^

	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructUndefined.construct(SafeConstructor.java:620)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:270)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:253)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:581)
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:213)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:557)
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:600)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:270)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:253)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:207)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:191)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:477)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:418)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:237)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:351)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:320)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:307)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.unmarshal(OperationSupport.java:734)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.load(BaseOperation.java:247)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.load(BaseOperation.java:88)
	at io.kaoto.backend.deployment.ClusterService.start(ClusterService.java:184)
	at io.kaoto.backend.deployment.ClusterService_Subclass.start$$superforward1(Unknown Source)
	at io.kaoto.backend.deployment.ClusterService_Subclass$$function$$5.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.opentelemetry.runtime.tracing.cdi.WithSpanInterceptor.span(WithSpanInterceptor.java:66)
	at io.quarkus.opentelemetry.runtime.tracing.cdi.WithSpanInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:33)
	at io.kaoto.backend.deployment.ClusterService_Subclass.start(Unknown Source)
	at io.kaoto.backend.deployment.ClusterService.start(ClusterService.java:109)
	at io.kaoto.backend.deployment.ClusterService_Subclass.start$$superforward1(Unknown Source)
	at io.kaoto.backend.deployment.ClusterService_Subclass$$function$$6.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.opentelemetry.runtime.tracing.cdi.WithSpanInterceptor.span(WithSpanInterceptor.java:66)
	at io.quarkus.opentelemetry.runtime.tracing.cdi.WithSpanInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:33)
	at io.kaoto.backend.deployment.ClusterService_Subclass.start(Unknown Source)
	at io.kaoto.backend.deployment.ClusterService_ClientProxy.start(Unknown Source)
	at io.kaoto.backend.api.resource.v1.DeploymentsResource.start(DeploymentsResource.java:106)
	at io.kaoto.backend.api.resource.v1.DeploymentsResource_ClientProxy.start(Unknown Source)
	at io.kaoto.backend.api.resource.v1.DeploymentsResource$quarkusrestinvoker$start_f48ac03cfdbbb66936f666149c43c5a58796bf5c.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:114)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Environment (please complete the following information):**

- Kaoto Version: main / latest
- Kubernetes 1.24 (KinD)

**Comment by Delawen** [comment]
This error is no longer on latest Kaoto.
