### ISSUE TITLE
[BUG] Empty response when adding a step to an empty branch

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-backend#512]
**Describe the bug**
On issuing a `POST` request to `/integrations?dsl=Camel%20Route` with [the following payload](https://gist.githubusercontent.com/kahboom/39ddb2c2f9aa7d9090d546aa4b364d4e/raw/9d650981790838e478698a28c786c7a1b09aa1ab/payload.json), there is no response from the backend.

**To Reproduce**
See https://github.com/KaotoIO/kaoto-ui/issues/1381

**Expected behavior**
A response with the correct JSON

**Logs**
Stack trace provided by @lordrip (thanks!):
```
2023-03-06 13:28:24,476 WARN  [io.kao.bac.api.ser.dep.DeploymentService] (executor-thread-40) Parser class io.kaoto.backend.api.service.deployment.generator.kamelet.KameletDeploymentGeneratorService_ClientProxythrew an unexpected error. : java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "io.kaoto.backend.model.parameter.Parameter.getValue()" is null
    at io.kaoto.backend.KamelPopulator.assignParameters(KamelPopulator.java:508)
    at io.kaoto.backend.KamelPopulator.getMarshalStep(KamelPopulator.java:492)
    at io.kaoto.backend.KamelPopulator.processStep(KamelPopulator.java:320)
    at io.kaoto.backend.KamelPopulator.getFlow(KamelPopulator.java:262)
    at io.kaoto.backend.KamelPopulator.populateKamelet(KamelPopulator.java:98)
    at io.kaoto.backend.model.deployment.kamelet.Kamelet.<init>(Kamelet.java:49)
    at io.kaoto.backend.api.service.deployment.generator.kamelet.KameletDeploymentGeneratorService.parse(KameletDeploymentGeneratorService.java:79)
    at io.kaoto.backend.api.service.deployment.generator.kamelet.KameletDeploymentGeneratorService_ClientProxy.parse(Unknown Source)
    at io.kaoto.backend.api.service.deployment.DeploymentService.crd(DeploymentService.java:86)
    at io.kaoto.backend.api.service.deployment.DeploymentService_Subclass.crd$$superforward1(Unknown Source)
    at io.kaoto.backend.api.service.deployment.DeploymentService_Subclass$$function$$1.apply(Unknown Source)
    at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
    at io.quarkus.opentelemetry.runtime.tracing.cdi.WithSpanInterceptor.span(WithSpanInterceptor.java:66)
    at io.quarkus.opentelemetry.runtime.tracing.cdi.WithSpanInterceptor_Bean.intercept(Unknown Source)
    at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
    at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
    at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:33)
    at io.kaoto.backend.api.service.deployment.DeploymentService_Subclass.crd(Unknown Source)
    at io.kaoto.backend.api.service.deployment.DeploymentService_ClientProxy.crd(Unknown Source)
    at io.kaoto.backend.api.resource.v1.IntegrationsResource.cdr(IntegrationsResource.java:85)
    at io.kaoto.backend.api.resource.v1.IntegrationsResource_ClientProxy.cdr(Unknown Source)
    at io.kaoto.backend.api.resource.v1.IntegrationsResource$quarkusrestinvoker$cdr_bda4f3154fddee7031592f0b55e0f34abe335178.invoke(Unknown Source)
    at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
    at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:114)
    at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
    at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
    at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
    at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
    at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:833)
```

**Environment (please complete the following information):**
 - OS: macOS & Fedora
 - Output of the mvn -version` command
```
$ mvn -version
Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)
Maven home: /opt/homebrew/Cellar/maven/3.8.5/libexec
Java version: 18.0.1, vendor: Homebrew, runtime: /opt/homebrew/Cellar/openjdk/18.0.1/libexec/openjdk.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "12.6", arch: "aarch64", family: "mac"
```
 - Kaoto Version: `0.7.2-dev`

**Additional context**

**Comment by igarashitm** [comment]
@kahboom while DSL type is set to `Camel Route`, the first step is `kamelet:source`, which should be invalid is it expected? - I'll try to send it as `Kamelet` instead in the meantime.

**Comment by kahboom** [comment]
>while DSL type is set to Camel Route, the first step is kamelet:source, which should be invalid - is it expected?
@Delawen this should not be valid, right?

@igarashitm Unless there is an issue where the mini catalog is not being updated when the DSL is changed, the steps should correspond to the DSL. Have you checked to see that the backend response is not showing `kamelet:source` as a step for the catalog, when specifying `Camel Route` DSL as a query param? This will tell us if problem is on the backend or frontend.
