### ISSUE TITLE
[BUG] Uncaught exception related to parsing in the CamelRouteStepParserService.getCamelRoute method

### ISSUE THREAD

**Issue by mkralik3** [KaotoIO/kaoto-backend#662]
**Describe the bug**
`.spec.definition.title` is null (`title: null`, without surrounding any apostrophes) for an initial empty Kamelet ~~which causes an exception[1] in the backend when the code is synced. After that, the null is surrounded by an apostrophe so after the second code sync, the issue is gone. Or when I change it to the empty string `title: ''`, the error is not shown.~~
If this option for setting the title is not in the UI, we can use same string as in the `.metadata.name`.
// enhancement for `title: null`: https://github.com/KaotoIO/kaoto-backend/pull/664 

//**edit**: The exception is not caused by null in title element. See https://github.com/KaotoIO/kaoto-backend/issues/662#issuecomment-1551161499  

[1]
```
2023-05-16 13:13:12,817 WARN  [io.kao.bac.api.res.v1.IntegrationsResource] (executor-thread-0) Parser class io.kaoto.backend.api.service.step.parser.camelroute.CamelRouteStepParserService_ClientProxythrew an unexpected error.: java.lang.ClassCastException: com.fasterxml.jackson.databind.node.ObjectNode cannot be cast to com.fasterxml.jackson.databind.node.ArrayNode
	at io.kaoto.backend.api.service.step.parser.camelroute.CamelRouteDeserializer.deserialize(CamelRouteDeserializer.java:32)
	at io.kaoto.backend.api.service.step.parser.camelroute.CamelRouteDeserializer.deserialize(CamelRouteDeserializer.java:19)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3677)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3645)
	at io.kaoto.backend.api.service.step.parser.camelroute.CamelRouteStepParserService.getCamelRoute(CamelRouteStepParserService.java:119)
	at io.kaoto.backend.api.service.step.parser.camelroute.CamelRouteStepParserService.appliesTo(CamelRouteStepParserService.java:112)
	at io.kaoto.backend.api.service.step.parser.camelroute.CamelRouteStepParserService_ClientProxy.appliesTo(Unknown Source)
	at io.kaoto.backend.api.resource.v1.IntegrationsResource.integration(IntegrationsResource.java:132)
	at io.kaoto.backend.api.resource.v1.IntegrationsResource_ClientProxy.integration(Unknown Source)
	at io.kaoto.backend.api.resource.v1.IntegrationsResource$quarkusrestinvoker$integration_a2f8369bb7dcf7cb17b1bb4f8473b027a51694dd.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:114)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@19.0.1/java.lang.Thread.run(Thread.java:1589)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)

2023-05-16 13:13:12,820 WARN  [io.kao.bac.api.res.v1.IntegrationsResource] (executor-thread-0) Gurl, the DSL you gave me is so wrong. This is a Kamelet not a null
```

**To Reproduce**
1. Open KaotoUI
2. In the settings, change to Kamelet
3. Open the source code editor and click on `Sync your code`
4. The error is shown in the backend log

**Expected behavior**

**Logs**
If applicable, add logs to help explain your problem.

**Environment (please complete the following information):**
- OS: Linux
- Browser: Firefox
- Version: 
   - Backend: main branch (uber jar, mvn 3.8.6, openjdk 19.0.2)
   - UI: main branch (yarn install, yarn start)

**Additional context**
Not able to reproduce with `1.0.0 (native-linux) ` , there is only warn that DSL is wrong ( which is correct ) 

Migrated from https://github.com/KaotoIO/kaoto-ui/issues/1803

**Comment by mkralik3** [comment]
I am debugging it and the root cause of that error is not due to the `null` in the title. Also I have missed that the exception is from [WARN log](https://github.com/KaotoIO/kaoto-backend/blob/main/camel-route-support/src/main/java/io/kaoto/backend/api/service/step/parser/camelroute/CamelRouteDeserializer.java#L32) only.

The UI calls API `v1/integrations` without `dsl` query param, so [dsl String](https://github.com/KaotoIO/kaoto-backend/blob/main/api/src/main/java/io/kaoto/backend/api/resource/v1/IntegrationsResource.java#L109) is `null`.
After that, [here](https://github.com/KaotoIO/kaoto-backend/blob/main/api/src/main/java/io/kaoto/backend/api/resource/v1/IntegrationsResource.java#L132) when the execution is going through `stepParserServices` collection and `CamelRouteStepParserService` is before `KameletStepParserService`, the exception ClassCastException is raised because the ArrayNode is expected instead of ObjectNode [here](https://github.com/KaotoIO/kaoto-backend/blob/main/camel-route-support/src/main/java/io/kaoto/backend/api/service/step/parser/camelroute/CamelRouteDeserializer.java#L32).

**Comment by mkralik3** [comment]
So I would say, it is not a bug and WARN exception is shown according to the order of that stepParserServices collection.

**Comment by mkralik3** [comment]
Reopen again. The appliesTo() should return only [true/false](https://github.com/KaotoIO/kaoto-backend/blob/main/services-interfaces/src/main/java/io/kaoto/backend/api/service/step/parser/StepParserService.java#L60) even if DSL is invalid/different. That exception should be catch [here](https://github.com/KaotoIO/kaoto-backend/blob/main/camel-route-support/src/main/java/io/kaoto/backend/api/service/step/parser/camelroute/CamelRouteStepParserService.java#L120) 

Also, please provide tests for appliesTo method for each StepParserService implementation to check if it returns the proper boolean according to DSL (valid or invalid) and no exceptions related to parsing.
