### ISSUE TITLE
[BUG] Can't load Kamelets

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-backend#68]
**Describe the bug**
Kamelets cause a deployment error in the UI, which replaces the YAML and the visualization.

**To Reproduce**

Uploading `Kamelet` file:
1. Upload the file attached (`Kamelet`)
2. Visualization is empty, see error

```bash
2022-05-30 10:31:39,570 WARN  [io.kao.bac.api.res.ViewDefinitionResource] (executor-thread-0) Parser class io.kaoto.backend.api.service.step.parser.kamelet.KameletStepParserService_ClientProxythrew an unexpected error.: java.lang.IllegalArgumentException: Error trying to parse.
	at io.kaoto.backend.api.service.step.parser.kamelet.KameletStepParserService.deepParse(KameletStepParserService.java:93)
	at io.kaoto.backend.api.service.step.parser.kamelet.KameletStepParserService_Subclass.deepParse$$superforward1(Unknown Source)
[..]
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `io.kaoto.backend.model.deployment.kamelet.KameletTypes` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('(2) out')
 at [Source: (StringReader); line: 59, column: 10] (through reference chain: io.kaoto.backend.model.deployment.kamelet.Kamelet["spec"]->io.kaoto.backend.model.deployment.kamelet.KameletSpec["types"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
[..]
```

```bash
2022-05-30 10:31:39,607 ERROR [io.kao.bac.api.res.IntegrationResource] (executor-thread-0) Error processing deployment.: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at java.base/java.util.Arrays$ArrayList.<init>(Arrays.java:4137)
	at java.base/java.util.Arrays.asList(Arrays.java:4122)
	at io.kaoto.backend.api.service.deployment.DeploymentService.crd(DeploymentService.java:38)
```

![Kapture 2022-05-30 at 10 35 02](https://user-images.githubusercontent.com/3844502/170963678-72271e2f-65ec-4d9a-8eed-84bd1ea470a4.gif)

Switching from `KameletBinding` to `Kamelet`:
1. Upload the file attached (`KameletBinding`)
3. Click on Settings cog button from Visualization
4. Under `Integration Type` select `Kamelet`, press Save.
5. See YAML has been updated to `Kamelet`
6. Type anything in the YAML editor to trigger an update to the Visualization
7. See error

![Kapture 2022-05-30 at 10 26 42](https://user-images.githubusercontent.com/3844502/170962284-96738645-ed31-4e60-83e3-bd200cdd6748.gif)

```bash
2022-05-30 10:26:31,062 WARN  [io.kao.bac.api.res.ViewDefinitionResource] (executor-thread-1) Parser class io.kaoto.backend.api.service.step.parser.kamelet.KameletStepParserService_ClientProxythrew an unexpected error.: java.lang.StringIndexOutOfBoundsException: Range [0, -1) out of bounds for length 21
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4589)
	at java.base/java.lang.String.substring(String.java:2703)
	at io.kaoto.backend.api.service.step.parser.kamelet.KameletStepParserService.processDefinedStep(KameletStepParserService.java:184)
	at io.kaoto.backend.api.service.step.parser.kamelet.KameletStepParserService.processStep(KameletStepParserService.java:126)
	at io.kaoto.backend.api.service.step.parser.kamelet.KameletStepParserService.processSpec(KameletStepParserService.java:107)
	at io.kaoto.backend.api.service.step.parser.kamelet.KameletStepParserService.deepParse(KameletStepParserService.java:91)
	at io.kaoto.backend.api.service.step.parser.kamelet.KameletStepParserService_Subclass.deepParse$$superforward1(Unknown Source)
[..]
```

```bash
2022-05-30 10:26:31,110 ERROR [io.kao.bac.api.res.IntegrationResource] (executor-thread-1) Error processing deployment.: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at java.base/java.util.Arrays$ArrayList.<init>(Arrays.java:4137)
	at java.base/java.util.Arrays.asList(Arrays.java:4122)
	at io.kaoto.backend.api.service.deployment.DeploymentService.crd(DeploymentService.java:38)
	at io.kaoto.backend.api.service.deployment.DeploymentService_Subclass.crd$$superforward1(Unknown Source)
```

**Expected behavior**
Users should be able to change between Kamelets and KameletBindings, and to upload a Kamelet specification.

**Logs**
If applicable, add logs to help explain your problem.

**Environment (please complete the following information):**
 - OS: macOS Monterey
 - Output of the `mvn -version` command: 3.8.5
 - Kaoto Version: 1.0

**Additional context**

`Kamelet` used:

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: twitter-search-source
  annotations:
    camel.apache.org/kamelet.icon: "data:image/svg+xml;base64,..." # Truncated (1)
    camel.apache.org/provider: "Apache Software Foundation"
  labels:
    camel.apache.org/kamelet.type: "source"
    camel.apache.org/kamelet.group: "Twitter"
spec:
  definition:
    title: "Twitter Search Source"
    description: |-
      Allows to get all tweets on particular keywords from Twitter.

      It requires tokens that can be obtained by creating an application
      in the Twitter developer portal: https://developer.twitter.com/.
    required:
    - keywords
    - apiKey
    - apiKeySecret
    - accessToken
    - accessTokenSecret
    properties:
      keywords:
        title: Keywords
        description: The keywords to use in the Twitter search (Supports Twitter standard operators)
        type: string
        example: "Apache Camel"
      apiKey:
        title: API Key
        description: The API Key from the Twitter application in the developer portal
        type: string
        format: password
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:password
      apiKeySecret:
        title: API Key Secret
        description: The API Key Secret from the Twitter application in the developer portal
        type: string
        format: password
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:password
      accessToken:
        title: Access Token
        description: The Access Token from the Twitter application in the developer portal
        type: string
        format: password
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:password
      accessTokenSecret:
        title: Access Token Secret
        description: The Access Token Secret from the Twitter application in the developer portal
        type: string
        format: password
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:password
  types: (2)
    out:
      mediaType: application/json
  flow: (3)
    from:
      uri: "twitter-search:{{keywords}}"
      parameters:
        accessToken: "{{accessToken}}"
        accessTokenSecret: "{{accessTokenSecret}}"
        consumerKey: "{{apiKey}}"
        consumerSecret: "{{apiKeySecret}}"
      steps:
      - marshal:
          json: {}
      - to: "kamelet:sink"
```

`KameletBinding` used for switching from `KameletBinding` to `Kamelet` manually:

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: twitter-search-source-binding
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: twitter-search-source
    properties:
      keywords: "Apache Camel"
      apiKey: "your own"
      apiKeySecret: "your own"
      accessToken: "your own"
      accessTokenSecret: "your own"
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: kafka-sink
    properties:
      brokers: "The Brokers"
      password: "The Password"
      topic: "The Topic Names"
      username: "The Username"
```

**Comment by kahboom** [comment]
On second thought, the file upload one might be a problem in the UI, going to investigate this today.

**Comment by Delawen** [comment]
Checking this. Sometimes the frontend reverts back to KameletBinding (backend's fault?) and some parts of that kamelet are not parsed by the backend.

**Comment by Delawen** [comment]
And it contains some numbers like `(2)` which breaks the YAML and makes it invalid.

**Comment by Delawen** [comment]
I guess a mix of https://github.com/KaotoIO/kaoto-backend/pull/74 and https://github.com/KaotoIO/kaoto-ui/pull/516 fixed this.

Although a refactor of the API would benefit the kamelet handling further.
