### ISSUE TITLE
[BUG] Documentation GitHub workflow is broken: Invalid miniclass definition:  DSLSpecification

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-backend#728]
**Describe the bug**

```
> @ docs-api /home/runner/work/kaoto-backend/kaoto-backend
> leafdoc -t leafdoc-templates/plain -o docs/index.html -c "🐱" leafdoc-templates/index.leafdoc */src/main/java/ -e true -x .java

Invalid miniclass definition:  DSLSpecification
Error: No class/namespace set when parsing through:
null
🐱method identifier: String

Returns the identifier of the supported language.

This must be unique on the whole Kaoto instance and relates the deployments and parsers services with the DSL
specification.
file:///home/runner/work/kaoto-backend/kaoto-backend/node_modules/leafdoc/src/leafdoc.mjs:371
					if (!currentNamespace.supersections.hasOwnProperty(dt)) {
					                      ^

TypeError: Cannot read property 'supersections' of undefined
    at Leafdoc.addStr (file:///home/runner/work/kaoto-backend/kaoto-backend/node_modules/leafdoc/src/leafdoc.mjs:371:28)
    at Leafdoc.addBuffer (file:///home/runner/work/kaoto-backend/kaoto-backend/node_modules/leafdoc/src/leafdoc.mjs:193:15)
    at Leafdoc.addFile (file:///home/runner/work/kaoto-backend/kaoto-backend/node_modules/leafdoc/src/leafdoc.mjs:185:15)
    at Leafdoc.addDir (file:///home/runner/work/kaoto-backend/kaoto-backend/node_modules/leafdoc/src/leafdoc.mjs:174:10)
    at Leafdoc.addDir (file:///home/runner/work/kaoto-backend/kaoto-backend/node_modules/leafdoc/src/leafdoc.mjs:169:10)
    at Leafdoc.addDir (file:///home/runner/work/kaoto-backend/kaoto-backend/node_modules/leafdoc/src/leafdoc.mjs:169:10)
    at Leafdoc.addDir (file:///home/runner/work/kaoto-backend/kaoto-backend/node_modules/leafdoc/src/leafdoc.mjs:169:10)
    at Leafdoc.addDir (file:///home/runner/work/kaoto-backend/kaoto-backend/node_modules/leafdoc/src/leafdoc.mjs:169:10)
    at Leafdoc.addDir (file:///home/runner/work/kaoto-backend/kaoto-backend/node_modules/leafdoc/src/leafdoc.mjs:169:10)
    at Leafdoc.addDir (file:///home/runner/work/kaoto-backend/kaoto-backend/node_modules/leafdoc/src/leafdoc.mjs:169:10)
```

**To Reproduce**

**Expected behavior**

Documentation GitHub action working

**Logs**
If applicable, add logs to help explain your problem.

**Environment (please complete the following information):**

**Additional context**

failure was relatively hidden because another job is failign for a long time and so there was a red cross on all commit of main branch for a very long time https://github.com/KaotoIO/kaoto-backend/issues/530

**Comment by apupier** [comment]
first broken build: https://github.com/KaotoIO/kaoto-backend/actions/runs/5129989303
